### ISSUE TITLE
Bug restore

### ISSUE THREAD

**Issue by oliv79** [ysde/grafana-backup-tool#103]
Hi, 
I have a bug when i want to restore a backup.
Can anyone help me ?

grafana-backup restore _OUTPUT_/202010221644.tar.gz
...

########################################

Traceback (most recent call last):
  File "/bin/grafana-backup", line 11, in <module>
    load_entry_point('grafana-backup==1.1.3', 'console_scripts', 'grafana-backup')()
  File "/usr/lib/python2.7/site-packages/grafana_backup/cli.py", line 46, in main
    restore(args, settings)
  File "/usr/lib/python2.7/site-packages/grafana_backup/restore.py", line 45, in main
    with tempfile.TemporaryDirectory() as tmpdir:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'

**Comment by acjohnson** [comment]
@oliv79 looks like python 2 support is broken by the use of tempfile that is only in python 3. If you can use Python 3 I would recommend you switch. That said this bug should be fairly easy to work around in the code and I will take a look

**Comment by acjohnson** [comment]
https://github.com/ysde/grafana-backup-tool/pull/104 fixes this if you are wanting this fixed @ysde

**Comment by oliv79** [comment]
the workaround using python3 works. It's ok for me. Thanks.
