### ISSUE TITLE
Dashboards with same name in different folders not restored

### ISSUE THREAD

**Issue by Maddin-M** [ysde/grafana-backup-tool#113]
Title says it all. After deleting all dashboards and folders only one of the dashboard with the same name is being restored.

Dashboards saved:
![grafik](https://user-images.githubusercontent.com/34421118/101623217-68fd7800-3a18-11eb-996c-bef43b2c16ce.png)

Dashboards after restore:
![grafik](https://user-images.githubusercontent.com/34421118/101623599-f771f980-3a18-11eb-89d4-0c0fd8f8dc0c.png)

**Comment by acjohnson** [comment]
Thanks for letting us know @Maddin-M!
