### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by MrBlood01** [ysde/grafana-backup-tool#115]
Hi, first I wanted to congratulate you on the fantastic tool. It works properly. But would there be the possibility to download the plug-ins too?

Also I wanted to know how can I backup grafana on one version and then restore on another different grafana server with different IP. It's possible?

Thanks in advance!

**Comment by ysde** [comment]
Hi @MrBlood01 

Currently I couldn't find a way to backup plugin by using Grafana's api.

If you find something please let me know or you can issue a PR for it :D

Many Thanks

**Comment by MrBlood01** [comment]
Hello! First of all, thank you for answering me. Okay, if you can find anything I'll let you know.

I wanted to ask you something. If I backup a grafana server (192.168.1.12) can I copy it to a second server (192.168.1.50) by modifying the config file?

Thanks!

**Comment by ysde** [comment]
Hi @MrBlood01 

What do you mean by modifying `config file` ? What's the config file ?

You can restore components that this tool have backed-up to another server, it's totally ok.

Thank you

**Comment by MrBlood01** [comment]
This is the "conf" file to configure to do the backup right?
[https://github.com/ysde/grafana-backup-tool/blob/master/grafana_backup/conf/grafanaSettings.json](url)

I wanted to know, to do a backup restore from one server to another how should I do? Different PCs and IPs of course.

Thanks!

**Comment by Mikey1993** [comment]
> 
> 
> This is the "conf" file to configure to do the backup right?
> 
> This: grafana_backup/conf/grafanaSettings.json
> 
> I wanted to know, to do a backup restore from one server to another how should I do? Different PCs and IPs of course.
> 
> Thanks!

Yes, this is the default config file if not specified otherwise.

**Comment by MrBlood01** [comment]
> Yes, this is the default config file if not specified otherwise.

So to restore the backup I just need to change the IP in the "config" file?

**Comment by Mikey1993** [comment]
> > Yes, this is the default config file if not specified otherwise.
> > @Mikey1993
> 
> So to restore the backup I just need to change the IP in the "config" file?

@MrBlood01,
For the restoring you will need to change all the relevant values under the `global` and `grafana` sections of the json configuration of the new Grafana instance you are trying to restore to.

After that you will be able to run in the command line:
`grafana-backup restore {path/to/backup_file.tar.gz}`
For the restore process to start.

Good luck :)

**Comment by MrBlood01** [comment]
But the changes must be made on the "grafanaSettings.json" file right?

**Comment by acjohnson** [comment]
https://github.com/ysde/grafana-backup-tool#configuration use `~/.grafana-backup.json` instead

**Comment by MrBlood01** [comment]
> https://github.com/ysde/grafana-backup-tool#configuration use `~/.grafana-backup.json` instead

I tried to change the ip in this file. But it doesn't work, the system doesn't restore. Could it be an API key issue?

**Comment by acjohnson** [comment]
@MrBlood01 it certainly could be an API key issue. Did you happen to receive an error message indicating an API key failure? If so logic may follow that your could try creating a new API key on the destination grafana server but if you haven't already realized this then I recommend that you give it a shot it may work, it might not, depending on what the error message is that you received and what the error code was, etc, etc. Troubleshooting is hard I agree but we are very happy to help you answer each and ever specific question you have just be sure to include as much detail as you can (or not) depending on what type of information you would like to share. Anyways happy to help please keep posting here until you feel things are solved! :smiley:

**Comment by MrBlood01** [comment]
@acjohnson First of all, thank you for the incredible kindness and availability. Then the problem is that I don't get any error messages. I run the "grafana-backup restore" command but nothing happens

**Comment by acjohnson** [comment]
@MrBlood01 subtlety is not my strong suit! I would love to help you further with this if you choose to proceed further with utilizing our team of experts at your disposal for your troubleshooting pleasure. Would you kindly consider posting as much information as possible to help us solve your unique dilemma. To be precise please include the following information to ensure I am able to understand your specific set up and configuration.

OS: (Windows, Linux Mac)
If Linux what distribution and version
Python version
Python packages installed (`pip freeze` would be super helpful!)
Installation steps that you followed (are you using a virtual environment?)
Configuration file `~/.grafana-backup.json` (you are welcome to redact your api key or not up to you)
Networking troubleshooting steps that you have followed (have you ensured you can connect to the target port and IP address using other tools such as netcat?)

**Comment by tonoriesco** [comment]
> @acjohnson First of all, thank you for the incredible kindness and availability. Then the problem is that I don't get any error messages. I run the "grafana-backup restore" command but nothing happens

Hi,

What a did/try:

I have a host A running Grafana version 6.X. I backup with the `grafana-backup save` with a A-config.json config, no problem. A.tar.gz is created. I inspected the file and looks OK. All the json's are there.

I have a host B that I installed Grafana 7.X. I backup with the tool with B-config.json, no problem. B.tar.gz is created.

Now, I use `grafana-backup restore A.tar.gz --config=B-config.json ` and apparently everything works. I mean, there are some errors, but mostly I get:

`restoring dashboard XXXX response status: 200 .... `

When I go to the Grafana B interface, nothing is there... Not a single dashboard.

**Comment by acjohnson** [comment]
I followed these steps and am able to successfully backup dashboards from a Grafana 6.x instance and restore to a Grafana 7.x instance. Please try these steps and let me know if you are still experiencing problems @tonoriesco @MrBlood01 

### Install grafana-backup from master branch
```shell
# sudo apt install virtualenv
# git clone https://github.com/ysde/grafana-backup-tool.git
# cd grafana-backup-tool
# virtualenv -p $(which python3) venv
# source venv/bin/activate
# pip install .

# grafana-backup --version
grafana-backup 1.1.7
```

### Launch Grafana docker containers
**Note: the grafana-6 container is listening on host port 3001**
```shell
# docker run -d --rm -p 3000:3000 --name grafana-7 grafana/grafana:7.3.7
# docker run -d --rm -p 3001:3000 --name grafana-6 grafana/grafana:6.7.5
```

### Create grafana-backup configs
```shell
cat << EOF > grafana-7.json
{
  "general": {
    "debug": true,
    "verify_ssl": false,
    "pretty_print": true
  },
  "grafana": {
    "url": "http://localhost:3000",
    "token": "",
    "default_password": "admin",
    "admin_account": "admin",
    "admin_password": "admin"
  }
}
EOF

cat << EOF > grafana-6.json
{
  "general": {
    "debug": true,
    "verify_ssl": false,
    "pretty_print": true
  },
  "grafana": {
    "url": "http://localhost:3001",
    "token": "",
    "default_password": "admin",
    "admin_account": "admin",
    "admin_password": "admin"
  }
}
EOF
```
### Create dashboards and API keys
- Login to grafana-6 instance `http://localhost:3001` create some dashboards as well as admin api key
  - Add new admin api key to `grafana-6.json`
    - `"token": "<api_key>",` 
- Login to grafana-7 instance `http://localhost:3000` create admin api key
  - Add new admin api key to `grafana-7.json`
    - `"token": "<api_key>",` 

### Backup/Restore
```shell
# grafana-backup save --config=grafana-6.json
# grafana-backup restore _OUTPUT_/202101260954.tar.gz --config=grafana-7.json
```

**Comment by tonoriesco** [comment]
> I followed these steps and am able to successfully backup dashboards from a Grafana 6.x instance and restore to a Grafana 7.x instance. Please try these steps and let me know if you are still experiencing problems @tonoriesco @MrBlood01
Hi @acjohnson

Works perfectly. I need to adjust the datasources, etc. but at least all the dashboards are there.

Thank you!

Tono.

**Comment by acjohnson** [comment]
@ysde any chance you could open up the wiki section on this repo so we can add the above steps as an example for others to follow?

**Comment by MrBlood01** [comment]
> @MrBlood01 subtlety is not my strong suit! I would love to help you further with this if you choose to proceed further with utilizing our team of experts at your disposal for your troubleshooting pleasure. Would you kindly consider posting as much information as possible to help us solve your unique dilemma. To be precise please include the following information to ensure I am able to understand your specific set up and configuration.
> 
> OS: (Windows, Linux Mac)
> If Linux what distribution and version
> Python version
> Python packages installed (`pip freeze` would be super helpful!)
> Installation steps that you followed (are you using a virtual environment?)
> Configuration file `~/.grafana-backup.json` (you are welcome to redact your api key or not up to you)
> Networking troubleshooting steps that you have followed (have you ensured you can connect to the target port and IP address using other tools such as netcat?)


Sure! I can give you some useful info:

1) It is obviously a Linux system, to be precise "Debian 10"
2) Python 3.7
3) As for python packages I have to check.
4) Yes, it is a virtual machine on VMware.

**Comment by MrBlood01** [comment]
> I followed these steps and am able to successfully backup dashboards from a Grafana 6.x instance and restore to a Grafana 7.x instance. Please try these steps and let me know if you are still experiencing problems @tonoriesco @MrBlood01
> 
> ### Install grafana-backup from master branch
> ```shell
> # sudo apt install virtualenv
> # git clone https://github.com/ysde/grafana-backup-tool.git
> # cd grafana-backup-tool
> # virtualenv -p $(which python3) venv
> # source venv/bin/activate
> # pip install .
> 
> # grafana-backup --version
> grafana-backup 1.1.7
> ```
> 
> ### Launch Grafana docker containers
> **Note: the grafana-6 container is listening on host port 3001**
> 
> ```shell
> # docker run -d --rm -p 3000:3000 --name grafana-7 grafana/grafana:7.3.7
> # docker run -d --rm -p 3001:3000 --name grafana-6 grafana/grafana:6.7.5
> ```
> 
> ### Create grafana-backup configs
> ```shell
> cat << EOF > grafana-7.json
> {
>   "general": {
>     "debug": true,
>     "verify_ssl": false,
>     "pretty_print": true
>   },
>   "grafana": {
>     "url": "http://localhost:3000",
>     "token": "",
>     "default_password": "admin",
>     "admin_account": "admin",
>     "admin_password": "admin"
>   }
> }
> EOF
> 
> cat << EOF > grafana-6.json
> {
>   "general": {
>     "debug": true,
>     "verify_ssl": false,
>     "pretty_print": true
>   },
>   "grafana": {
>     "url": "http://localhost:3001",
>     "token": "",
>     "default_password": "admin",
>     "admin_account": "admin",
>     "admin_password": "admin"
>   }
> }
> EOF
> ```
> 
> ### Create dashboards and API keys
> * Login to grafana-6 instance `http://localhost:3001` create some dashboards as well as admin api key
>   
>   * Add new admin api key to `grafana-6.json`
>     
>     * `"token": "<api_key>",`
> * Login to grafana-7 instance `http://localhost:3000` create admin api key
>   
>   * Add new admin api key to `grafana-7.json`
>     
>     * `"token": "<api_key>",`
> 
> ### Backup/Restore
> ```shell
> # grafana-backup save --config=grafana-6.json
> # grafana-backup restore _OUTPUT_/202101260954.tar.gz --config=grafana-7.json
> ```

So I have to create two "grafana Settings.json" files. One for each version of Grafana?
But with the same type of user, that (user: admin, pass: "whatever") but the API key different?

**Comment by acjohnson** [comment]
@MrBlood01 Yes! :smiley: :smiley: :smiley:

**Comment by MrBlood01** [comment]
Thank you so much guys. The tool works perfectly. Also thanks to the "crontab" command I was able to automate backups! 
Thank you very much to all of you for the help you have given me.

You are fantastic!
