### ISSUE TITLE
Push latest grafana-backup to pypi?

### ISSUE THREAD

**Issue by acjohnson** [ysde/grafana-backup-tool#125]
Do you agree we could/should push the current release of grafana-backup to pypi @ysde? Seems it has been stable for some time now.

**Comment by ysde** [comment]
sure, thank you for the reminding

**Comment by acjohnson** [comment]
Isn't the current version [1.1.7](https://github.com/ysde/grafana-backup-tool/blob/master/grafana_backup/constants.py#L4)? 

Also the package archive that is published to pypi has different code than the release archive https://github.com/ysde/grafana-backup-tool/archive/1.1.5.zip

**Comment by acjohnson** [comment]
@ysde can you take another look at this. I don't think the pypi release was done quite right. Either the version in 
`grafana-backup-tool/grafana_backup/constants.py` should be decremented or the version in pypi should be incremented.
