### ISSUE TITLE
Azure storage configuration

### ISSUE THREAD

**Issue by charlspjohn** [ysde/grafana-backup-tool#126]
Hi,

How can I configure Azure storage ? I can only see S3 configuration example file.

--
Thanks,
Charls

**Comment by acjohnson** [comment]
We need someone with Azure access to contribute storage support. Pull requests are welcome :smile:

**Comment by ysde** [comment]
Hi @charlspjohn 

@neallclark helped adding the Azure support.

Can you give it a try?

Thanks

**Comment by charlspjohn** [comment]
@ysde , it worked !
Thanks @neallclark
