### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by thinrope** [ysde/grafana-backup-tool#13]
From http://docs.python-requests.org/en/master/

> Note:
>
> The use of Python 3 is highly preferred over Python 2. Consider upgrading your applications and infrastructure if you find yourself still using Python 2 in production today. If you are using Python 3, congratulations — you are indeed a person of excellent taste. —Kenneth Reitz
>

This tool is one of the few in my systems that still works only with python2.7, please upgrade it to support python3, as well.

It looks simple enough to do with `futurize` (looks like only 'print()' is used), let me know if you prefer PR, or you'd rather hand-check it yourself.

**Comment by ysde** [comment]
Yeah, please help upgrade it to support Python3. 

PR is welcomed.

Thank you.

**Comment by ysde** [comment]
I've done the upgrade in 1eee871f3b06d53970cc362709b08be1e1dfb0ce.
