### ISSUE TITLE
Add support for Dashboard versions

### ISSUE THREAD

**Issue by fsperling** [ysde/grafana-backup-tool#145]
Hi,

First of all thanks for the awesome tool!

I would also like to backup and restore the dashboard versions.
https://grafana.com/docs/grafana/latest/http_api/dashboard_versions/
If there is interest in this feature I could try work on a PR for that.

Cheers,
Felix

**Comment by ysde** [comment]
Hi @fsperling  
Yeah sure, PRs are welcome :D

**Comment by fsperling** [comment]
I also wrote code to save dashboard versions. Its tricky/not possible to restore them with the Grafana API.
I based it on the branch with the snapshots, so I'll wait before I create another PR.
