### ISSUE TITLE
Add support for Snapshots

### ISSUE THREAD

**Issue by fsperling** [ysde/grafana-backup-tool#146]
Hi,

First of all thanks for the awesome tool!

I would also like to backup and restore the snapshots.
https://grafana.com/docs/grafana/latest/http_api/snapshot/
If there is interest in this feature I could try work on a PR for that.

Cheers,
Felix

**Comment by ysde** [comment]
Hi @fsperling  
Yeah sure, PRs are welcome :D

**Comment by fsperling** [comment]
Hi @ysde,
I've created a PR for this issue. Please let me know what you think.
https://github.com/ysde/grafana-backup-tool/pull/148
