### ISSUE TITLE
Add support for Annotations

### ISSUE THREAD

**Issue by fsperling** [ysde/grafana-backup-tool#147]
Hi,

First of all thanks for the awesome tool!

I would also like to backup and restore the annotations.
https://grafana.com/docs/grafana/latest/http_api/annotations/
If there is interest in this feature I could try work on a PR for that.

Cheers,
Felix

**Comment by ysde** [comment]
Hi @fsperling  
Yeah sure, PRs are welcome :D

**Comment by fsperling** [comment]
is part of PR https://github.com/ysde/grafana-backup-tool/pull/148
