### ISSUE TITLE
dashboards: {'message': 'Not found'} when running save

### ISSUE THREAD

**Issue by LukoJy3D** [ysde/grafana-backup-tool#165]
Hello guys, looking for insights here.

Dashboard backup is not generated when running `grafana-backup save`. Even though all dashboards are detected:
```
grafana health: http://localhost:3000/api/health
[DEBUG] status: 200
[DEBUG] body: {'commit': 'afb9e8e5f3', 'database': 'ok', 'version': '8.3.2'}
search dashboard in grafana: http://localhost:3000/api/search/?type=dash-db&limit=5000&page=1
[DEBUG] status: 200
There are 240 dashboards:
...
...
```

But for EVERY dashboard I get `{'message': 'Not found'}`:
```
query dashboard uri: http://localhost:3000/api/dashboards/db/lxc
[DEBUG] status: 404
[DEBUG] body: {'message': 'Not found'}
```

however if I try to curl with dashboard uid everything is good:
```
curl http://localhost:3000/api/dashboards/uid/3FSaVZriz
{
  "meta": {
    "type": "db",
    "canSave": true,
    "canEdit": true,
    "canAdmin": true,
    "canStar": true,
    "slug": "lxc",
    "url": "/d/3FSaVZriz/lxc",
    "expires": "0001-01-01T00:00:00Z",
    "created": "2021-12-13T12:40:33Z",
    "updated": "2021-12-13T12:48:20Z",
    "updatedBy": "admin",
    "createdBy": "admin",
    "version": 4,
    "hasAcl": false,
    "isFolder": false,
    "folderId": 0,
    "folderUid": "",
    "folderTitle": "General",
    "folderUrl": "",
    "provisioned": false,
    "provisionedExternalId": ""
```

I was wondering if anyone else ran into such issue?

**Comment by acjohnson** [comment]
@LukoJy3D it looks like `uid_support` check is failing and it is trying to lookup the dashboard using the `uri` `db/lxc` in your example.

`uid_support` is a feature that ensures backwards compat with older versions of Grafana.

Do you happen to see something like this at the beginning of the `grafana-backup save` output?

```
[Pre-Check] grafana uid feature check: calling 'search_dashboard'
search dashboard in grafana: http://localhost:3000/api/search/?type=dash-db&limit=1&page=1
[DEBUG] resp status: 200
[DEBUG] resp body: [{'id': 2, 'uid': 'U57XM32nz', 'title': 'foo', 'uri': 'db/foo', 'url': '/d/U57XM32nz/foo', 'slug': '', 'type': 'dash-db', 'tags': [], 'isStarred': False, 'sortMeta': 0}]
```

In the DEBUG response body you should have a field called `uid`. I wonder what would cause this check to fail since you seem to be running Grafana `8.3.2`...

**Comment by LukoJy3D** [comment]
Big thanks for taking time to look into this. 

I do see DEBUG response with uids, however does not seem like any `[Pre-check]` is being done:
```
[root@~]# /usr/local/bin/grafana-backup save
grafana health: http://localhost:3000/api/health
[DEBUG] status: 200
[DEBUG] body: {'commit': 'afb9e8e5f3', 'database': 'ok', 'version': '8.3.2'}
search dashboard in grafana: http://localhost:3000/api/search/?type=dash-db&limit=5000&page=1
[DEBUG] status: 200
[DEBUG] body: [{'id': 248, 'uid': '4JXP3h8Gk', 'title': '[Temp] Perf count', 'uri': 'db/temp-perf-count', 'url': '/d/4JXP3h8Gk/temp-perf-count', 'slug': '', 'type': 'dash-db', 'tags': [], 'isStarred': False, 'folderId': 11, 'folderUid': 'l2i-MwcGk', 'folderTitle': 'Test folder', 'folderUrl': '/dashboards/f/l2i-MwcGk/test-folder', 'sortMeta': 0},
...
...
There are 240 dashboards:
name: [Temp] Perf count
...
...
########################################

query dashboard uri: http://localhost:3000/api/dashboards/db/temp-perf-count
[DEBUG] status: 404
[DEBUG] body: {'message': 'Not found'}
```

using latest grafana-backup version (1.2.2), my pip is 21.1 ant Python 3.8.9

**Comment by acjohnson** [comment]
@LukoJy3D something very strange is happening here... In your output for example you show a printed string `grafana health: http://localhost:3000/api/health`
...however that string is not possible to be printed when you look at the source code of version 1.2.2
```
grafana_backup/dashboardApi.py:    print("\n[Pre-Check] grafana health check: {0}".format(url))
```
So I'm a bit confused if what you shared in your last post was just sanitized manually with some mistakes? Or perhaps something else is going on such as you are using an old version of grafana-backup-tool that happens to be in your path or something...

**Comment by LukoJy3D** [comment]
Big thanks for all the insights @acjohnson. Apparently we were using old version under wrong path `/usr/local/bin/grafana-backup` and newest version was installed under `/usr/local/pyenv/shims/grafana-backup` when we switched to pip. Made some config tweaks, change logic a bit and now it works as intended. Thanks once again
