### ISSUE TITLE
 can't encode character u'\u2013' 

### ISSUE THREAD

**Issue by dgttm** [ysde/grafana-backup-tool#17]
Hi, 
first of all, thank you for your work.

I ran into the following issue. Its working for most of my dashboards, but some encounter the following issue while saveDashboards.py exports it:

query dashboard uri: db/pxc-galera-graphs, status: 200
Traceback (most recent call last):
  File "/grafana-backup-tool/saveDashboards.py", line 48, in <module>
    get_indivisual_dashboard_setting_and_save(dashboards)
  File "grafana-backup-tool/saveDashboards.py", line 41, in get_indivisual_dashboard_setting_and_save
    save_dashboard_setting(board['title'], board['uid'], status_code_and_content[1])
  File "grafana-backup-tool/saveDashboards.py", line 33, in save_dashboard_setting
    f.write(dashboard_settings)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 21376: ordinal not in range(128)

I tried with python 2.7 and 3.6, same issue.

thanks a lot!

**Comment by dgttm** [comment]
I found a solution. adding this to the header exports my dashboards now.

import sys
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by ysde** [comment]
Sorry for the late response.
Thank you for sharing the findings.

I'll check how to prevent this problem.
Thanks
