### ISSUE TITLE
Basic auth failed

### ISSUE THREAD

**Issue by Shotte** [ysde/grafana-backup-tool#19]
I ceated and added an API key as suggested in your documentation but cannot get the sript working due to authentication errors.

```
########################################

search dashboard in grafana:
get dashboards failed, status: 401, msg: {"message":"Basic auth failed"}

########################################
```

I'm using Grafana v6.1.3 (9504db8)

Any hints for me?

Regards

**Comment by ysde** [comment]
Hi @Shotte 

It seems you don't have the right permission to call the API.

Did you create a token and set it in grafanaSettings.py ? (GRAFANA_TOKEN)

Maybe you can try first creating a API token with Admin Role to see it works or not.

https://grafana.com/docs/http_api/auth/
https://grafana.com/docs/permissions/overview/

FYI

**Comment by crzykidd** [comment]
I had this same issue with a "view" API key.   Made it admin key and it works fine.

**Comment by Shotte** [comment]
Hi @ysde and @crzykidd ,

thank you for your responses and hints, but I already used an admin key/token. Might there be an incompatibility based on some "special" Grafana settings (any special combination for login/guests/etc settings)?

Regards

**Comment by ysde** [comment]
Hi @Shotte 

I think......
Maybe you didn't copy the token completely ?

Because I've made such mistake once :p.

There is a  "=" at the end of the token, did you copy it to `grafanaSetting.py` ?

Is that your situation ?
