### ISSUE TITLE
Grafana cloud versions are not matched by the regex matcher.

### ISSUE THREAD

**Issue by vsmanu** [ysde/grafana-backup-tool#215]
If you try to use the tool against the Grafana cloud, the backup progresses but ends with an error during the grafana version check. 

Grafana backup tool version : 
Python version : 3.11.2

`lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging. version.InvalidVersion: Invalid version: '9.5.2-cloud.2.0cb5a501'
`

**Comment by acjohnson** [comment]
@vsmanu if you have a chance I'd be curious if the latest version (1.3.3) works to backup a Grafana cloud instance. Thanks!
