### ISSUE TITLE
Using the latest version of grafana 9.5.3, when backing up through the service account, it can be successfully backed up, but the package is not compressed after the backup

### ISSUE THREAD

**Issue by ilanni2460** [ysde/grafana-backup-tool#219]
Using the latest version of grafana 9.5.3, when backing up through the service account, it can be successfully backed up, but the package is not compressed after the backup

The backup command is:
`
docker run --user $(id -u):$(id -g) --rm --name grafana-backup-tool -v /etc/localtime:/etc/localtime:ro -e GRAFANA_TOKEN="glsa_4ZlYeIWSRVbSl_97db98a0" -e GRAFANA_URL=http://172.168.1.130:3000 -e VERIFY_SSL=False -v /opt/backup/:/opt/grafana-backup-tool/_OUTPUT_   ysde/docker-grafana-backup-tool
`
![1](https://github.com/ysde/grafana-backup-tool/assets/5058391/1d9e2e2d-2e79-4f13-9174-6ad0dbc22c0f)

**Comment by chriz-active** [comment]
Testing with grafana v9.5.5 and some v10 using a service-account-token runs through for us.

- are you sure that your backup went through completely?
- until the backup is finished I can see intermediate files lying around, which are collected in a late step for the compressed tar.gz-file
