### ISSUE TITLE
KeyError: 'uid' in saveDashboards.py

### ISSUE THREAD

**Issue by saurabtanej** [ysde/grafana-backup-tool#22]
I am trying to use this perfectly suited backup script for me.
I have the requirements already.
```
python --version
Python 2.7.12
```
```
pip install requests
You are using pip version 6.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
```

but still the script is facing with key error. Below is the error:
```
Traceback (most recent call last):
  File "/home/ec2-user/grafana-backup-tool/saveDashboards.py", line 52, in <module>
    get_indivisual_dashboard_setting_and_save(dashboards)
  File "/home/ec2-user/grafana-backup-tool/saveDashboards.py", line 43, in get_indivisual_dashboard_setting_and_save
    board['uid'],
KeyError: 'uid'
```

**Comment by ysde** [comment]
Hi @saurabtanej 
Can you set `debug=True` which is in the grafanaSetting.py and show me the response Grafana API responded ? 

It seems that the response content lack of `uid` field.

Thank you

**Comment by saurabtanej** [comment]
Hi @ysde , Its already running in debug mode. 

Its able to list the dashboard, response is also 200 so there shouldnt be anything wrong with the authentication. But the content seems to be missing uid which fails the script.

**Comment by ysde** [comment]
Hi @saurabtanej

Which grafana version do you use ?

**Comment by saurabtanej** [comment]
Hi @ysde my grafana version is  Grafana v4.4.3

**Comment by saurabtanej** [comment]
Hi @ysde , do you know why it could happen?

**Comment by ysde** [comment]
Hi @saurabtanej 

I think it's because of the version v4.4.3.

The version you used seems that it doesn't contain `uid` field.
https://grafana.com/docs/v4.4/http_api/dashboard/

Can you upgrade your grafana version ?
I can also try to make a compatible version for Grafana v4.4.3.

FYI

**Comment by saurabtanej** [comment]
@ysde , I upgraded garafana version to 6 and script worked fine.

Thanks!
