### ISSUE TITLE
[bug] Notification policy spelling

### ISSUE THREAD

**Issue by DerekTBrown** [ysde/grafana-backup-tool#254]
Notification policies is misspelled, resulting in files with a misspelled name:

https://github.com/ysde/grafana-backup-tool/blob/1e14e490268209d4b2e0f9c21bbaff9d9cc764e1/grafana_backup/save_notification_policies.py#L37

https://github.com/ysde/grafana-backup-tool/blob/1e14e490268209d4b2e0f9c21bbaff9d9cc764e1/grafana_backup/save_notification_policies.py#L61

**Comment by declan-fitzpatrick** [comment]
Sorted in #262. 

Note that [restoring notification policies are not yet supported](https://github.com/ysde/grafana-backup-tool/issues/227#issuecomment-1635461417) and [disabled](https://github.com/ysde/grafana-backup-tool/blob/1e14e490268209d4b2e0f9c21bbaff9d9cc764e1/grafana_backup/restore.py#L100).
