### ISSUE TITLE
Introduce some kind of DEBUG flag?

### ISSUE THREAD

**Issue by thinrope** [ysde/grafana-backup-tool#26]
Now that everything works (tm), may be it is time to tidy out the default output and introduce some kind of debug/verbose flag...
I'd suggest "-d" and print a help message like:
````bash
echo "Please re-run with DEBUG enabled for troubleshooting:"
echo "$0 -d $*"
exit -1
````
upon error.

**Comment by ysde** [comment]
Sure, It's good to make the usage more friendly.
I'll work on this when I'm free :D

**Comment by pmhausen** [comment]
Seconded. I'd leave the "debug yes/no" configuration in the config file ...

**Comment by gkotian** [comment]
I think this issue can be closed right? There [seems to exist](https://github.com/ysde/grafana-backup-tool/blob/master/grafana_backup/grafanaSettings.py#L21) a debug flag that can be set to True/False.

**Comment by acjohnson** [comment]
Yes, the debug option is there and is enabled by default (could be debated if it should be disabled by default instead.)
