### ISSUE TITLE
TypeError in saveDatasources.py

### ISSUE THREAD

**Issue by IngaFeick** [ysde/grafana-backup-tool#3]
Not sure if this tool is supposed to work against grafana version 4 aswell. If not then please just close the ticket.

Python 2.7.9
Both grafana env variables are set and correct (I know because the saveDashboards.py works like a charm)
Grafana version: 4.1.0

```
user@server:/github/grafana-backup-tool$ python saveDatasources.py ~/tmp
search datasources in grafana:
There are 1 datasources:
Traceback (most recent call last):
  File "saveDatasources.py", line 27, in <module>
    datasources = get_all_datasources_and_save()
  File "saveDatasources.py", line 23, in get_all_datasources_and_save
    save_datasource(datasource['name'], datasource)
TypeError: string indices must be integers
```

The $datasource contains only `u'message'`

**Comment by ysde** [comment]
Hi IngaFeick
I've tested on Grafana 4.0.2, it's ok.
I'll test it with Grafana 4.1.0

Thank you for your feedback.

**Comment by ysde** [comment]
Hi @IngaFeick 

I've tested with Grafana 4.1.0
My datasource and dashboards are all fine and can be saved and restored.

I'm thinking maybe there's some situations like special characters that break the code, can you provide me your datasource name?

Thank you.

**Comment by The-smooth-operator** [comment]
I get the same error when the token is invalid. Note that I've printed the datasource object. 
It'd be cool to add some token validation.
There are 1 datasources:
{u'message': u'Invalid Basic Auth Header'}
Traceback (most recent call last):
  File "/Users/alberto/repos/grafana-backup-tool/saveDatasources.py", line 28, in <module>
    datasources = get_all_datasources_and_save()
  File "/Users/alberto/repos/grafana-backup-tool/saveDatasources.py", line 24, in get_all_datasources_and_save
    save_datasource(datasource['name'], datasource)
TypeError: string indices must be integers`
`

**Comment by The-smooth-operator** [comment]
So, it appears that in order to be able to list the data sources, the key has to have "Admin" permissions level, while for listing the dashboards "Viewer" is enough. 
Most likely this was the problem experienced by @IngaFeick

**Comment by IngaFeick** [comment]
@The-smooth-operator affirmative. Thanks a lot for the hint, problem solved. I'm closing this.
