### ISSUE TITLE
Backup tar file extraction fails

### ISSUE THREAD

**Issue by danrue** [ysde/grafana-backup-tool#31]
I've tried using the docker container to back up my grafana instance. Everything appears to work fine, but when I try extracting the resulting tar file I see the following error:

```
# tar xvzf 2019-06-21T16\:19\:59.tar.gz 
tar (child): Cannot connect to 2019-06-21T16: resolve failed

gzip: stdin: unexpected end of file
tar: Child returned status 128
tar: Error is not recoverable: exiting now
```

It seems that if I extract the tar file from a directory higher than it exists, it works, but if I try to extract it from its current directory, it does not.

```
root@8861f06da2eb:/opt/grafana-backup-tool/_OUTPUT_# tar xvzf 2019-06-21T16\:22\:39.tar.gz 
tar (child): Cannot connect to 2019-06-21T16: resolve failed

gzip: stdin: unexpected end of file
tar: Child returned status 128
tar: Error is not recoverable: exiting now
root@8861f06da2eb:/opt/grafana-backup-tool/_OUTPUT_# cd ..
root@8861f06da2eb:/opt/grafana-backup-tool# tar xvzf _OUTPUT_/2019-06-21T16\:22\:39.tar.gz 
_OUTPUT_/dashboards/2019-06-21T16:22:39/
_OUTPUT_/dashboards/2019-06-21T16:22:39/VLIFWnMWk.dashboard
_OUTPUT_/dashboards/2019-06-21T16:22:39/tnvBiR4Zk.dashboard
_OUTPUT_/dashboards/2019-06-21T16:22:39/77G4tjmWk.dashboard
_OUTPUT_/dashboards/2019-06-21T16:22:39/2co7gfmZk.dashboard
_OUTPUT_/dashboards/2019-06-21T16:22:39/dashboards_201906211622.txt
_OUTPUT_/datasources/2019-06-21T16:22:39/
_OUTPUT_/folders/2019-06-21T16:22:39/
_OUTPUT_/folders/2019-06-21T16:22:39/folders_201906211622.txt
_OUTPUT_/folders/2019-06-21T16:22:39/UWX_f8WZk.folder
_OUTPUT_/folders/2019-06-21T16:22:39/_CWXfUWWz.folder
```

**Comment by wargamez** [comment]
I think it has to do with the filename used containing ":", and tar thinks this is some remote server tar thingy ... Try to move the file to backup.tar before you issue the tar xvzf command on it

**Comment by ysde** [comment]
Hi @danrue 

I think @wargamez is right. 

According to this https://unix.stackexchange.com/questions/13377/tar-extraction-depends-on-filename

Can you try using `--force-local` on your `tar` command according the link above ?

I tested on my Mac is ok though.

Thank you

**Comment by danrue** [comment]
Hi! Thanks for taking a look at this and explaining the issue.

I think it should be fixed (which probably means avoiding the colons?) - it's hard for casual users to trust backup software that creates tar files that can't be extracted without special knowledge (there are probably a lot of users who either never try to extract the archive before they need it, or, who try, get that error, and then go away forever).

**Comment by ysde** [comment]
@danrue 

Yeah, I agree with you. 

I've changed the file name format.

Maybe you can give it try ?

Thanks for the advices.

**Comment by danrue** [comment]
Thanks @ysde it works great!
