### ISSUE TITLE
directory name '2019-07-lOT07:33:06' with : not compatible with Windows

### ISSUE THREAD

**Issue by GETandSELECT** [ysde/grafana-backup-tool#35]
Hi

I run `backup_grafana.sh` which creates a tarball. When you unpack the tarball there are directories like `2019-07-lOT07:33:06` which is not compatible with windows. I upload the contents of tarball to Git repo.

Please replace : with -

During Git checkout of grafana-backup the Windows guys get:

```
fatal: cannot create directory at 'grafana-backup-tool/dashboards/2019-07-lOT07:33:06':
Invalid argument
```

thanks

**Comment by ysde** [comment]
Hi @GETandSELECT 

I have changed the file name format.

Can you give it a try ?

Thank you.

**Comment by GETandSELECT** [comment]
thanks.
