### ISSUE TITLE
can you please add backup to alerts channels 

### ISSUE THREAD

**Issue by Fadih** [ysde/grafana-backup-tool#36]
hi 
thank you man you have a very good tool
i would like to ask you if you can add backup and restore to alerts channels
https://grafana.com/docs/http_api/alerting_notification_channels/ 
thanks

**Comment by ysde** [comment]
Hi @Fadih 

Thank you for the compliment.

Recently busy on work. I need some time doing this.

Thank you

**Comment by Fadih** [comment]
thanks

**Comment by Fadih** [comment]
hey my friend any estimation time for this feature ??
thanks

**Comment by ysde** [comment]
Hi @Fadih 

Sorry for the late response.

Probably this weekend.

Thanks!

**Comment by ysde** [comment]
Hi @Fadih 

Hi @GETandSELECT 

I have pushed the codes for alert channels.

Can you give it a try ?

Thank you.

**Comment by Fadih** [comment]
Thank you man im on vacation this week,i will check when i come back 
Thank you

**Comment by zot24** [comment]
I did test it @Fadih @ysde and found and issue on my case submit a PR to fix my use case that might be related with my specific version of Grafana (v5.2.4) didn't have time to check others https://github.com/ysde/grafana-backup-tool/pull/38

**Comment by Fadih** [comment]
hi
thank you my friend its working fine to me  @zot24 im using grafana version v6.1.0
