### ISSUE TITLE
Restore example (from docker)

### ISSUE THREAD

**Issue by cabrinoob** [ysde/grafana-backup-tool#39]
Hi,
I'am trying to use grafana-backup to backup and restore my grafana dashboards.

The backup works fine but I don't know how tu use the restore method.

**I want to use it from docker.**

For the backup I'am using this :

```
docker run --rm --name grafana-backup-tool \
   -e GRAFANA_TOKEN={YOUR_GRAFANA_TOKEN} \
   -e GRAFANA_URL={YOUR_GRAFANA_URL} \
   -v {YOUR_BACKUP_FOLDER_ON_THE_HOST}:/opt/grafana-backup-tool/_OUTPUT_  \
   ysde/docker-grafana-backup-tool
```
But for the restore I don't know what to do. When I look inside the Dockerfile I see that there is an ENTRYPOINT assigned to **backup_grafana.sh**.

thank you for your help

**Comment by ysde** [comment]
Sorry I only thought about backup. I'll make a version of restore and backup and add explanations in README.

Thanks

**Comment by ysde** [comment]
Hi @cabrinoob 

I've added in the latest commit.  

Can you give it a try ?

Thank you

**Comment by cabrinoob** [comment]
Thank you
