### ISSUE TITLE
Restored datasources are "locked"

### ISSUE THREAD

**Issue by cabrinoob** [ysde/grafana-backup-tool#40]
Hi,
Thank you for your work.

I have a strange problem but I don't know if it's a grafana or a backup-tool problem :

I'am running Grafana on a kubernetes cluster in a "prometheus" namespace. The backup phase works fine.

To test the restore, I create another grafana instance in a "test" namespace. The restore phase seems to work fine, but I need to update the "prometheus" datasource to make it point to the prometheus datasource. So I go in the datasource menu an I have this : 

![](https://i.imgur.com/HYNRt9P.png)

_The datasource was added by config and cannot be modified using the UI_

I cannot modify anything here and I cannot delete it. Is there something to do from the backup-tool?

Thank you

**Comment by ysde** [comment]
Hi @cabrinoob 

Sorry I haven't used namespace before.

I'll test it when I'm available.

Thanks for the feedback.

**Comment by ysde** [comment]
Hi @cabrinoob 

According to the message in your picture. 
The datasource was created by config files.

I cannot reproduce the problem by using backup tool.

But I can reproduce the problem you mentioned by using [grafana provisioning](https://grafana.com/docs/administration/provisioning/)
https://xuxinkun.github.io/2018/11/27/grafana-provisioning/

Can you help check is there any .yml or .yaml files under folder `/etc/grafana/provisioning/datasources` ?

Thank you

**Comment by cabrinoob** [comment]
Yes, I have 1 *datasources.yaml* file with the definition of my prometheus datasource

**Comment by ysde** [comment]
So can we conclude that the _lock_ issue is caused by _datasources.yaml_ , not the backup-tool (It uses only grafana api to do restore and backup)?
