### ISSUE TITLE
Custom headers?

### ISSUE THREAD

**Issue by dbaumann** [ysde/grafana-backup-tool#45]
In my case, Grafana is sitting behind a load balancer which routes based on the Host header.

**Comment by danielmotaleite** [comment]
Please merge this, i also need to pass the host header to correctly identify the vhost and can't use the host header value directly because it have google oauth protecting it

**Comment by ysde** [comment]
Hi @dbaumann, @danielmotaleite , is it better that use another name like `CUSTOM_HEADERS` instead of `GRAFANA_HEADERS`?  Since it's not used by Grafana server and can be customized all by our selves.

Thank you

**Comment by ysde** [comment]
Merged :)

Thanks
