### ISSUE TITLE
GRAFANA_HEADERS enviroment variable is not optional as stated

### ISSUE THREAD

**Issue by brandon-vargas** [ysde/grafana-backup-tool#48]
Even though the README states the GRAFANA_HEADERS is an optional environment varible, when i do not include it i get this error: `    EXTRA_HEADERS = dict(h.split(':') for h in os.getenv('GRAFANA_HEADERS').split(',') if 'GRAFANA_HEADERS' in os.environ)
AttributeError: 'NoneType' object has no attribute 'split'`

I also attempted to setting GRAFANA_HEADERS equal to an empty string, i get a different error here: `ValueError: dictionary update sequence element #0 has length 1; 2 is required` 

Below is a pull request to a solution for this error. 
https://github.com/ysde/grafana-backup-tool/pull/47

**Comment by ysde** [comment]
Hi @brandon-vargas 

I've responed in the code review. Would you take a look at it.

Thank you for the help.

**Comment by brandon-vargas** [comment]
The pull request has been updated to reflect a working dict comprehension. 
here: https://github.com/ysde/grafana-backup-tool/pull/47

**Comment by ysde** [comment]
The code has been merged. 

Thank you
