### ISSUE TITLE
Polish and release

### ISSUE THREAD

**Issue by amotl** [ysde/grafana-backup-tool#50]
Dear @ysde,

first things first: Thanks for conceiving this excellent utility.

After taking a look, I recognized the module has not been added to PyPI yet. It would be cool to add an appropriate `setup.py` and - while being at it - to wrap the functionality of `backup_grafana.sh`/`restore_grafana.sh` within respective [Python console script entrypoints](https://amir.rachum.com/blog/2017/07/28/python-entry-points/).

With kind regards,
Andreas.

**Comment by ysde** [comment]
Hi @amotl 

Thank you.

Honestly, I'm not familiar with PyPI. I only know I can `pip install` something.

I'll read the link and try to wrap them and add to PyPI.

By the way, helps are very welcome !

Thank you

**Comment by amotl** [comment]
Dear @ysde,

thanks for your feedback. I am always happy to help but have to share my time between other things which take my attention. However, please feel free to ping me on this if you don't hear back from me.

With kind regards,
Andreas.

**Comment by acjohnson** [comment]
@ysde Thank you for this great and nearly complete tool. From a functionality perspective this appears to give me exactly what I want.

I think what would tie it all together is to implement a CLI component using argparse or docopt or something similar which would get rid of `backup_grafana.sh` and `restore_grafana.sh` and utilize setup.py entrypoints as @amotl suggested.

I would like to help with this if you are interested and could file a pull request in the near future but this will be a fairly substantial series of commits.

**Comment by acjohnson** [comment]
https://github.com/ysde/grafana-backup-tool/pull/65

**Comment by acjohnson** [comment]
@amotl @ysde #65 has been merged this issue can be closed IMO

**Comment by ysde** [comment]
Thank you for the advices. @amotl 
Thank you for the help to refactor it. @acjohnson 

[https://pypi.org/project/grafana-backup/1.0.0/]()

**Comment by amotl** [comment]
Thanks a bunch, @acjohnson and @ysde. This has turned out pretty well!
