### ISSUE TITLE
Recent changes made to grafanaSettings.py breaks Python 2.7 compatibility

### ISSUE THREAD

**Issue by pwnell** [ysde/grafana-backup-tool#54]
The unpacking operator used in grafanaSettings.py in the most recent version breaks compatibility with Python 2.7 as the unpacking operator (**) for EXTRA_HEADERS is not supported in versions of Python before 3.5.

So perhaps just update your README.

**Comment by ysde** [comment]
Hi @pwnell 

Thanks for the feedback.
I didn't notice that.

I've updated the code. 

Can you give it a try if you have free time?

Thank you very much

**Comment by nkastanas** [comment]
in python 2.6.6 (yes i know)

**Comment by ysde** [comment]
@nkastanas  ok, thanks for the advice.
