### ISSUE TITLE
left_ver_newer_than_right_ver(resp['version'], "6.2.0")

### ISSUE THREAD

**Issue by Flodu31** [ysde/grafana-backup-tool#56]
Hello,
Thanks for the share.
I've the following error:

`grafana health: https://monitoring.domain.com/api/health
/home/florent/.local/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'monitoring.domain.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[DEBUG] status: 200
[DEBUG] body: {u'commit': u'65dbd7cadc', u'version': u'7.0.0-c1fa1cd2pre', u'database': u'ok'}
Traceback (most recent call last):
  File "/tmp/grafana-backup-tool/src/save_dashboards.py", line 70, in <module>
    is_api_support_page_param = left_ver_newer_than_right_ver(resp['version'], "6.2.0")
  File "/tmp/grafana-backup-tool/src/commons.py", line 6, in left_ver_newer_than_right_ver
    return convertVersion(current_version) > convertVersion(specefic_version)
  File "/tmp/grafana-backup-tool/src/commons.py", line 5, in convertVersion
    return int(''.join(ver.split(".")))
ValueError: invalid literal for int() with base 10: '700-c1fa1cd2pre'`

Any idea?
Thanks.
Florent

**Comment by ysde** [comment]
Hi @Flodu31 

Can you help check the version of your Grafana?

Maybe it's the same case of https://github.com/ysde/grafana-backup-tool/issues/37

If it's same issue, I'll fix it asap.

Thank you

**Comment by Flodu31** [comment]
Yes, same issue. 
I've version Grafana v7.0.0-c1fa1cd2pre (65dbd7cadc)
I removed everything in the if condition and it works fine.
Thanks.
Florent
