### ISSUE TITLE
Supporting Users and Orgs?

### ISSUE THREAD

**Issue by thebrennus** [ysde/grafana-backup-tool#57]
Is there any way this could be expanded to support backup/restore of users and orgs?
In my environment we have multiple organizations with different users/privileges per org.

**Comment by ysde** [comment]
Hi @thebrennus 

If Grafana has the corresponded API for creating and downloading  users and orgs, then it can be done.

I think it can be done.
https://grafana.com/docs/grafana/latest/http_api/org/#create-organization

Thank you.

**Comment by ysde** [comment]
Hi @thebrennus 

I add this feature in the latest commit.
FYI

Many thanks
