### ISSUE TITLE
Failed to establish a new connection: [Errno 110]

### ISSUE THREAD

**Issue by f0ff38** [ysde/grafana-backup-tool#63]
Hi!
Using grafana-backup-tool in docker I get the following error:
`TimeoutError: [Errno 110] Connection timed out`
[trace.log](https://github.com/ysde/grafana-backup-tool/files/4688550/trace.log)
Centos 7
Grafana v6.7.0-2a2568f6pre
Grafana API token validation successful.
I would be grateful for any advice.

**Comment by Mikey1993** [comment]
Are you sure your grafana instance is available on http://192.168.123.81:8110 ?
Are you able to browse to it?

**Comment by f0ff38** [comment]
> Вы уверены, что ваш экземпляр grafana доступен по [адресу http://192.168.123.81:8110](http://192.168.123.81:8110) ?
> Вы можете перейти к нему?

Hi, Mikey!
Yes of course.

**Comment by Mikey1993** [comment]
I'm sorry, but I am unsure what is the reason you are getting timed out then.
Maybe some firewall rules are blocking the connection?

**Comment by f0ff38** [comment]
Only iptables over netfilter is enabled, but there is a rule for this host, otherwise the grafana check would not work.
Anyway thanks for trying to help!

**Comment by ysde** [comment]
@Mikey1993 
Thanks for the help !

Hi @f0ff38 
According to the log....  it seems the backup program cannot connect to your grafana server.
May I know what's your environment looks like?
Did your grafana run in docker? 
Did your grafana and backup-docker program run in the same host ?

Thank you

**Comment by f0ff38** [comment]
Hi @ysde
Thx for the answer!
Grafana runs in Docker on another host on the same LAN.
Here is the output from the host where docker-grafana-backup-tool is running:
```
curl -I http://192.168.123.81:8082/api/health
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Expires: -1
Pragma: no-cache
X-Frame-Options: deny
Date: Thu, 04 Jun 2020 08:01:07 GMT
```

**Comment by ysde** [comment]
Hi @f0ff38 

Can you try adding --net=host when you run the grafana-backup-tool's docker command?
And see if it works ?

```
docker run --rm --net=host --name grafana-backup-tool \
   -e GRAFANA_TOKEN=<api_token> \
   -e GRAFANA_URL=http://192.168.123.81:8110 \
   -v /opt/grafana-backup-tool/:/opt/grafana-backup-tool/_OUTPUT_  \
   ysde/docker-grafana-backup-tool
```

**Comment by f0ff38** [comment]
Hi @ysde
This Works Great!
There was such an error:
```
search alert channels in grafana: http://192.168.123.81:8082/api/alert-notifications
[DEBUG] status: 403
[DEBUG] body: {'message': 'Permission denied'}
query alert channels failed, status: 403, msg: {'message': 'Permission denied'}
```
I do not use Grafana alerts, but perhaps this information will be useful.
Thank you very much!

**Comment by Mikey1993** [comment]
@f0ff38 ,
Looks like you don't have permissions,
are you using an `Admin` role for API Token that you are using?

**Comment by f0ff38** [comment]
Hi @Mikey1993 
Thx for the answer!
There are no errors with administrator rights. I only need copies of the panels, for this, read permission is enough.

**Comment by ysde** [comment]
Ok great~
Glad you solved the problem.
