### ISSUE TITLE
All folders empty

### ISSUE THREAD

**Issue by HamishKerr** [ysde/grafana-backup-tool#64]
Hello.
Thank you for your code. It works very well for me so far, except that the folders it creates when running a backup are empty. It does create a tar.gz file which has the folders inside which are not empty (the backup is working and reading my grafana), however the folders "alert_channels", "dashboards", "data_sources" and "folders" in the root _OUTPUT_ folder are empty.
Is this supposed to be the case or should those folders have the files in them?
Thank you very much
Hamish

**Comment by ysde** [comment]
Hi @HamishKerr 

Thank you.

The files are deleted when backed-up file .tar.gz generated.

If it's confusing, maybe it can be improved  by also removing the folders ?

**Comment by ysde** [comment]
Hi @HamishKerr 

I removed the empty folders in the latest commit. Please give it a try.
FYI

Many thanks
