### ISSUE TITLE
Token left on purpose?

### ISSUE THREAD

**Issue by tiagorodriguessimoes** [ysde/grafana-backup-tool#66]
https://github.com/ysde/grafana-backup-tool/blob/fc3ff95ae618d403deb8dbc7a3158a11b6f3be42/src/conf/grafanaSettings.py#L4

**Comment by Mikey1993** [comment]
@ysde 
Even if it's functional, I am sure it was just for example/testing?

**Comment by ysde** [comment]
Yes, it's for example usage.

I thought that way people can know "This place should be the token in." and know what does the token look like.

Sometimes people miss the final equals sign "=" when fill in this field. (I have done this before :D
