### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by acjohnson** [ysde/grafana-backup-tool#67]
@ysde let me know how you want to proceed but I think these instructions should work to get it published to PyPI if you want to try and follow these steps: https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives

**Comment by ysde** [comment]
Hi @acjohnson 

It works !
https://pypi.org/project/grafana-backup/1.0.0/

Thank you

**Comment by acjohnson** [comment]
Nice!
