### ISSUE TITLE
Can only backup 1000 dashboards

### ISSUE THREAD

**Issue by tehlers320** [ysde/grafana-backup-tool#7]
This is due to a limit in grafna that is hard coded https://github.com/grafana/grafana/blob/50a1feb90a5535ff2ec4f6242e47e4e9209d7575/pkg/services/sqlstore/dashboard.go#L153

**Comment by thinrope** [comment]
Looks like there is a new 'limit' param and it is honored (after 5.0.x)
https://github.com/grafana/grafana/blob/v5.4.x/pkg/services/search/handlers.go#L33

Apparently work from https://github.com/grafana/grafana/pull/8504

Not sure what is the default of 'limit', can someone with >1000dashboards test?

**Comment by ysde** [comment]
Hi guys

I've tested this. There is a query parameter "limit" in [dashboard search api](http://docs.grafana.org/http_api/folder_dashboard_search/)

The default is 1000 if you don't specify the "limit" parameter.

I set this to 100000 currently.  68f2945937f450c96afb4fedf682bd31bdbfce62
I think the possibility of creating dashboards over 100000 is very little right. 

Thanks
