### ISSUE TITLE
Handle API errors with exit code

### ISSUE THREAD

**Issue by pkubiak** [ysde/grafana-backup-tool#72]
Hi, I have recently noticed that tool doesn't handle Grafan API errors well.

In case of providing wrong Grafana Token, API replay with status `401` and following log is printed:

```
search alert channels in grafana: http://192.168.0.25:8081/api/alert-notifications
[DEBUG] status: 401
[DEBUG] body: {'message': 'Invalid API key'}
query alert channels failed, status: 401, msg: {'message': 'Invalid API key'}
```

But the tool works as usual, it creates empty archive and returns without errors.

Maybe it would be better to indicate such error (and probably other) with exit code and don't produce malformed archive files?  It would be helpful especially when script is run automatically.

Kind regards,
Paweł

**Comment by acjohnson** [comment]
#73

**Comment by ysde** [comment]
Hi @pkubiak 

@acjohnson helped add the feature.

FYI

**Comment by acjohnson** [comment]
#76

**Comment by pkubiak** [comment]
Super, thanks :) will you bump version of pypi package?
