### ISSUE TITLE
TypeError: health_check

### ISSUE THREAD

**Issue by bcar-github** [ysde/grafana-backup-tool#77]
https://github.com/ysde/grafana-backup-tool/blob/7a9d3ec410d5416d7a6969b5041728445b9415d0/grafana_backup/api_checks.py#L10
    (status, json_resp) = health_check(grafana_url, http_get_headers, verify_ssl, debug)

leads to:  TypeError: health_check() missing 1 required positional argument: 'debug'

see: 
https://github.com/ysde/grafana-backup-tool/blob/master/grafana_backup/dashboardApi.py#L5
def health_check(grafana_url, http_get_headers, verify_ssl, client_cert, debug)

fix: call health_check with expected args

**Comment by JPfeifer21** [comment]
@ysde pls revert the last commit, as the latest tool version doesn't work anymore.

**Comment by acjohnson** [comment]
@JPfeifer21 @ysde my bad, should have tested after the rebase... PR incoming

**Comment by JPfeifer21** [comment]
@acjohnson No worries :)

**Comment by acjohnson** [comment]
#78

**Comment by ysde** [comment]
Merged the latest commit.

Thanks @JPfeifer21  @acjohnson
