### ISSUE TITLE
Does the token have to exist after migration?

### ISSUE THREAD

**Issue by chinseone** [ysde/grafana-backup-tool#8]
This is not an issue but a question.

So we generated an API token on one Grafana instance and used the script to migrate some dashboards. After that we accidentally deleted the API token on the instance, and keep getting unauthorized error. So I'm wondering if this token is required even after migration?

**Comment by ysde** [comment]
I think the token is needed when you are trying to use the Grafana API.

**Comment by chinseone** [comment]
Mine isn't the latest either, maybe it's the datasource problem. Thanks anyway.

Li
