### ISSUE TITLE
Don't include aws and grafana token configs when building pypi package

### ISSUE THREAD

**Issue by tedpearson** [ysde/grafana-backup-tool#81]
Just installed latest version from git, and found that when I use env vars instead of config files, the aws upload section always attempts an upload using the dummy config values in grafanaSettings.json (bucket_name, et. al). It's currently impossible to avoid the aws upload step when using env vars for conf because the conf directory is packaged up into the installation in setup.py. Also there's a default grafana token in there as well which seems not smart either?

I'm thinking maybe there needs to be an example conf in addition to the default conf, to showcase the aws configs? Not everyone (aka me) wants the tool to upload to aws (I'm uploading to backblaze b2).

**Comment by OleksandrMykytenko** [comment]
I've managed to bypass it via setting `AWS_S3_BUCKET_NAME` env var to `""`. Then, S3 upload is just skipped and does not throw any exceptions.

**Comment by acjohnson** [comment]
I agree the default config is fine for some things but not if it forces users to set variables to empty strings...

**Comment by acjohnson** [comment]
#82
