### ISSUE TITLE
tarfile options not valid in python2

### ISSUE THREAD

**Issue by tedpearson** [ysde/grafana-backup-tool#83]
https://github.com/ysde/grafana-backup-tool/blob/9b89588ba5c41e6da77b6d180ce337ebd3d576a7/grafana_backup/archive.py#L18

If you want to continue to support python 2.7, you'll want to change this to `w:gz` instead of `x:gz`. Or just remove Python 2.7 from requirements in the readme. :)

**Comment by ysde** [comment]
Hi @tedpearson 

Thanks!
