### ISSUE TITLE
Getting the following errors when restoring from S3.

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [ysde/grafana-backup-tool#92]
I am getting the following errors, see below, when running the restore process. I am running this in ECS as a docker container, the backup process ran without issue. The backup file is located at the top of the S3 bucket.  I am running the same container just with RESTORE  true, and ARCHIVE_FILE  202009161750.tar.gz Environment Variables added to the container definition inside the ECS task definition. I am also running Grafana 7.0.0. I'm not sure if this error is due to the version of Grafana I am running and there is a difference in the APIs but I can't think of it being anything else. If it was I feel like I would see a different error. Thanks!

Error:
raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

**Comment by acjohnson** [comment]
@rmccarthy-ellevation as of now `grafana-backup-tool` requires the `AWS_S3_BUCKET_KEY` environment variable (or json config entry) to be set to a folder nested in the s3 bucket, so putting the backup in the top of the S3 bucket won't work without a slight code modification.

The default folder name (key) is `grafana-backup` so if you simply create a folder with that name and move the backup archive to that location it should pick it up, or you can override the default key name to whatever you choose.

**Comment by rmccarthy-ellevation** [comment]
Awesome, I think you are right in that being my issue, I will add the key and close this ticket if no there issues arise. Thanks!

**Comment by acjohnson** [comment]
@rmccarthy-ellevation No problem and thanks!

**Comment by rmccarthy-ellevation** [comment]
@acjohnson Awesome that worked, thanks for the help and quick reply.

**Comment by tommyjcarpenter** [comment]
@acjohnson I vote to reopen this issue.

I can successfully save to S3, but even after following these instructions, I cannot _restore_ from S3. 

My config looks like:
```
"aws": {
        "s3_bucket_name": "XXX-grafana-backups",
        "s3_bucket_key": "grafana-backup",
        "default_region": "us-east-1",
        "access_key_id": XXX
        "secret_access_key": XXX
    }
```

In S3, in that inner folder, I can see my tar files

But when executing this, 

```

########################################

[Pre-Check] Server status is 'OK' !!

########################################

Download archives from S3:
Traceback (most recent call last):
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/bin/grafana-backup", line 8, in <module>
    sys.exit(main())
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/grafana_backup/cli.py", line 46, in main
    restore(args, settings)
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/grafana_backup/restore.py", line 39, in main
    s3_data = s3_download(args, settings)
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/grafana_backup/s3_download.py", line 30, in main
    s3_data = s3_object.get()['Body']
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/tommycarpenter/.pyenv/versions/grafanabackup2/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

If I delete the S3 section from my config file, I can restore locally.

**Comment by acjohnson** [comment]
I just tested this, can you follow these steps and let me know if you have a different result?

Install grafana-backup to a clean virtualenv
```
git clone https://github.com/ysde/grafana-backup-tool.git
cd grafana-backup-tool
virtualenv -p $(which python3) venv
source venv/bin/activate
pip install .
```

Start two instances of grafana, one for backup and one for restore
```
docker run -d --rm --name=grafana-backup -p 3000:3000 grafana/grafana
docker run -d --rm --name=grafana-restore -p 3001:3000 grafana/grafana
```
Browse to `http://localhost:3000` login with admin:admin and create a new admin API key for backup
Browse to `http://localhost:3001` login with admin:admin and create a new admin API key for restore

Run the backup
```
export GRAFANA_TOKEN=<grafana-backup container admin api key>
export GRAFANA_URL=http://localhost:3000
export VERIFY_SSL=False
export AWS_S3_BUCKET_NAME=<aws_s3_bucket_name>
export AWS_S3_BUCKET_KEY=grafana-backup
export AWS_ACCESS_KEY_ID=<aws_access_key_id>
export AWS_SECRET_ACCESS_KEY=<aws_secret_access_key>
export AWS_DEFAULT_REGION=<aws_default_region>

grafana-backup save
```
Ensure the backup file has been uploaded to S3 in the proper location before continuing

Run the restore
```
export GRAFANA_TOKEN=<grafana-restore container admin api key>
export GRAFANA_URL=http://localhost:3001
export VERIFY_SSL=False
export AWS_S3_BUCKET_NAME=<aws_s3_bucket_name>
export AWS_S3_BUCKET_KEY=grafana-backup
export AWS_ACCESS_KEY_ID=<aws_access_key_id>
export AWS_SECRET_ACCESS_KEY=<aws_secret_access_key>
export AWS_DEFAULT_REGION=<aws_default_region>

grafana-backup restore <backup_filename>.tar.gz
```

**Comment by tommyjcarpenter** [comment]
@acjohnson I have figured out the issue  =) and have a UI proposal. 

The issue was the `grafanabackup restore XXX` where `XXX` itself does not exist in that S3 folder, as in the wrong tarball name. 

This is why save worked; because it doesn't take or care about the XXX, it generates it. 

My proposal would be to catch the stack trace above (never want to blow a stacktrace on a detectable condition) and print an error like "the file `XXX.tar.gz` does not exist in {bucket_name}/{folder_name}." I think this error message would be much clearer.

**Comment by acjohnson** [comment]
Good suggestion, and prs are welcome it you decide to tackle this yourself. It would be nice if the error handling was more clear for this condition.

**Comment by tommyjcarpenter** [comment]
Another potential suggestion is to have the restore be more verbose about the target, which is what led to this confusion; i have local files, and s3 files

```
restore local _OUTPUT_/XXX.tar.gz
restore s3 XXX.tar.gz
```

what happened to me is I was doing `restore onlylocal.tar.gz` and it was "by default" looking in s3, but it only existed locally. 

WIth these commands, it would be obvious what the "order" of restoration targets is maybe?

**Comment by acjohnson** [comment]
sure command line arguments to specify archive location would be nice to have as well!

**Comment by tommyjcarpenter** [comment]
I submitted a PR: https://github.com/ysde/grafana-backup-tool/pull/134

There seem to be no tests in this repo so I don't want to take on the second suggestion at the current time
