### ISSUE TITLE
[ERROR] Backing up organizations needs to set GRAFANA_ADMIN_ACCOUNT and GRAFANA_ADMIN_PASSWORD first.

### ISSUE THREAD

**Issue by alexrc20** [ysde/grafana-backup-tool#95]
Is it possible to authenticate only with the token with an admin role? Just for not writting the password in the json settings file.

**Comment by ysde** [comment]
Hi @alexrc20 

When backing up User and organization needs http basic auth. (According to [grafana official documents](https://grafana.com/docs/grafana/latest/http_api/org/#admin-organizations-api))

You can set account and password in the ENV variable `GRAFANA_ADMIN_ACCOUNT`,  `GRAFANA_ADMIN_PASSWORD` if you don't want to put them in the settings file.

Or you can base64 encode your account and password, then put in the ENV variable `GRAFANA_BASIC_AUTH`, it will look like this 
`GRAFANA_BASIC_AUTH=YWRtaW46YWRtaW4=`

FYI
