### ISSUE TITLE
Other S3-compatible providers

### ISSUE THREAD

**Issue by tombh** [ysde/grafana-backup-tool#97]
At the moment only AWS S3 is supported. This isn't a major problem as `grafana-backup` can just be used without its native S3 support and manual steps can be taken to upload. But at the least, would you be open to adding something like `s3cmd` to the Docker image? It'd simply need this line:

`RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing s3cmd`

**Comment by acjohnson** [comment]
I think some sort of post-backup hook command would be nice to add to both the grafana-backup cli as well as the docker image

**Comment by aminmr** [comment]
In fact, there will be object storage platforms which compatible with s3 and it would be grateful to have this compatibility in this fantastic repo.

**Comment by acjohnson** [comment]
I tested this finally with minio and it works great so closing this issue
